/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import renamer.MovieData;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cwlin
 */
public class MovieInfoDialog extends javax.swing.JDialog {

	private boolean confirmResult = false;

	/**
	 * Creates new form MovieInfoDialog
	 */
	public MovieInfoDialog(java.awt.Frame parent, boolean modal, MovieData data, String message) {
		super(parent, modal);
		initComponents();
		this.updateTableInfo(data);
		this.setMessage(message);
		this.setVisible(true);
	}

	public static boolean showConfirmMessage(java.awt.Frame parent, MovieData data, String message) {
		MovieInfoDialog dialog = new MovieInfoDialog(parent, true, data, message);
		return dialog.getConfirmResult();
	}

	public void setMessage(String message) {
		this.jLabel2.setText(message);
	}

	public boolean getConfirmResult() {
		return this.confirmResult;
	}

	public void updateTableInfo(MovieData data) {
		File parentFile = data.file.getParentFile();
		DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
		model.setValueAt("Fullname", 0, 0);
		model.setValueAt(data.file.getName(), 0, 1);
		model.setValueAt("Chinese name", 1, 0);
		model.setValueAt(data.getChineseName(), 1, 1);
		model.setValueAt("English name", 2, 0);
		model.setValueAt(data.getEnglishName(), 2, 1);
		model.setValueAt("Release date", 2, 0);
		model.setValueAt(data.getReleaseDate(), 2, 1);
		model.setValueAt("IMDB Rating", 3, 0);
		model.setValueAt(data.imdbRating, 3, 1);
		model.setValueAt("IMDB Votes", 4, 0);
		model.setValueAt(data.imdbVotes, 4, 1);
		model.setValueAt("Path", 5, 0);
		model.setValueAt(parentFile.getAbsoluteFile(), 5, 1);
		model.setValueAt("Current Directory Name", 6, 0);
		model.setValueAt(parentFile.getName(), 6, 1);
		model.setValueAt("Changed Name", 7, 0);
		model.setValueAt(data.toString(), 7, 1);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Column Name", "Value"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Movie Info:");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Yes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		this.confirmResult = true;
		this.setVisible(false);
		this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		this.confirmResult = false;
		this.setVisible(false);
		this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
